import type { Insight } from "@/lib/types";

const KIND_META: Record<Insight["kind"], { dot: string; label: string }> = {
  trend: { dot: "var(--color-ai)", label: "TREND" },
  risk: { dot: "var(--color-danger)", label: "RISK" },
  opportunity: { dot: "var(--color-electric)", label: "OPPORTUNITY" },
  milestone: { dot: "var(--color-money)", label: "MILESTONE" },
};

/**
 * The Intelligence Ticker — a continuously scrolling band of proactive
 * insights generated by the Overseer layer. Pauses on hover.
 */
export function IntelligenceTicker({ insights }: { insights: Insight[] }) {
  const items = [...insights, ...insights]; // duplicate for seamless loop

  return (
    <div className="surface flex items-center overflow-hidden py-2.5">
      <div className="flex shrink-0 items-center gap-2 border-r border-[var(--color-line)] px-4">
        <span className="live-dot h-1.5 w-1.5 rounded-full bg-ai" />
        <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-ai">
          Overseer
        </span>
      </div>
      <div className="relative flex-1 overflow-hidden">
        <div className="ticker-track gap-10 px-6">
          {items.map((ins, i) => {
            const meta = KIND_META[ins.kind];
            return (
              <span key={`${ins.id}-${i}`} className="inline-flex items-center gap-2.5 text-sm">
                <span className="h-1.5 w-1.5 rounded-full" style={{ background: meta.dot }} />
                <span className="font-mono text-[10px] tracking-wider text-fg-faint">
                  {meta.label}
                </span>
                <span className="text-fg">{ins.title}</span>
              </span>
            );
          })}
        </div>
      </div>
    </div>
  );
}
